spring:
  application:
    name: t1HoldingAccount
  jpa:
    show-sql: true
  aop:
    auto: true
    proxy-target-class: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "org.example.dto,org.example.aspects.starter.dto"
        spring.json.type.mapping: "ClientProductMessage:org.example.dto.ClientProductMessage, CardCreateDto:org.example.dto.CardCreateDto, TransactionMessageDto:org.example.dto.TransactionMessageDto, PaymentMessageDto:org.example.dto.PaymentMessageDto, ErrorLogMessage:org.example.aspects.starter.dto.ErrorLogMessage"
    consumer:
      group-id: account-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "org.example.dto"
        spring.json.type.mapping: "ClientProductMessage:org.example.dto.ClientProductMessage, CardCreateDto:org.example.dto.CardCreateDto, TransactionMessageDto:org.example.dto.TransactionMessageDto, PaymentMessageDto:org.example.dto.PaymentMessageDto"
        request.timeout.ms: 30000
        session.timeout.ms: 10000
        heartbeat.interval.ms: 3000
  datasource:
    url: jdbc:postgresql://account_db:5432/account_db
    username: postgres
    password: 123
    hibernate:
      ddl-auto: update

server:
  port: 8080

kafka:
  topics:
    client-products: client_products
    client-cards: client_cards
    client-transactions: client_transactions
    client-payments: client_payments
    service-logs: service_logs

aspects:
  datasource:
    enabled: true
    kafka-enabled: true
    fallback-to-database: true
    kafka-topic: "service_logs"
  metric:
    enabled: false
  cache:
    enabled: false

cache-config:
  card-cache: 600000
  account-cache: 900000

logging:
  level:
    org.springframework.aop: DEBUG
    org.example.aspect: TRACE
    org.apache.kafka: WARN
    org.springframework.kafka: INFO